In [1]:
## module gaussElimin
""" x = gaussElimin(a,b).
Solves [a]{b} = {x} by Gauss elimination.
"""
import numpy as np
def gaussElimin(a,b):
    n = len(b)
    
# Elimination Phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
            
# Back substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
        
    return b

a = np.array([[4,1,-1], [1,3,1], [2,-1,-2]])
b = np.array([12,18,-3])

print("Hasil Metode Gauss Eliminasi")
print(gaussElimin(a,b))

Hasil Metode Gauss Eliminasi
[4 3 3]


In [2]:
import numpy as np
#Iterasi Persamaan Gaus
# Membuat nilai nol dibawah diagonal matriks
def GEBS(A,B):
  n = len(B) # n berfungsi untuk mengembalikan panjang B
  for k in range(0,n-1): #iterasi dari 0 sampai nilai n-1 
    for i in range(k+1,n): #iterasi dari K+1 sampai nilai n
      if A[i,k] != 0.0:
        X = AB[k,k] / AB[i,k] #mencari pembagi untuk baris ke-i
        AB[i] = AB[k] - X*AB[i] #operasi perhitungan
        print("\n Eliminiasi gauss\n", AB)

#Iterasi Subtitusi
# Mencari nilai setiap variabel 
def subs(A,B):
  n = len(B) # n berfungsi untuk mengembalikan panjang B
  for k in range(n-1,-1,-1): #iterasi elemen matriks dari n-1 sampai -1
    AB[k] = AB[k] /AB[k,k] 
    for i in range (k-1, -1,-1): #iterasi untuk mendapatkan penyelesaiannya
      X = AB[k,k] / AB[i,k]
      AB[i] = AB[k] - X*AB[i] 
  print("\n Subtitusi\n", AB)     
  Hasil= AB[:,3]
  print("\n Hasil \n", Hasil)
  
A = np.array([[4,1,-1],
              [1,3,1],
              [2,-1,-2]], float
)

B = np.array([[12],
              [18],
              [-3]], float
)

AB = np.hstack([A,B])   # berfungsi untuk menggabung matriks A dan B 
print("\n")
print(GEBS(A,B))
print(subs(A,B))




 Eliminiasi gauss
 [[  4.   1.  -1.  12.]
 [  0. -11.  -5. -60.]
 [  2.  -1.  -2.  -3.]]

 Eliminiasi gauss
 [[  4.   1.  -1.  12.]
 [  0. -11.  -5. -60.]
 [  0.   3.   3.  18.]]

 Eliminiasi gauss
 [[  4.   1.  -1.  12.]
 [  0. -11.  -5. -60.]
 [  0.   0.   6.   6.]]
None

 Subtitusi
 [[ 1. -0.  0.  2.]
 [-0.  1. -0.  5.]
 [ 0.  0.  1.  1.]]

 Hasil 
 [2. 5. 1.]
None
